### PR TITLE
Print the Fibonacci series for n=20 #45

### PR DESCRIPTION
**Pull request by bidetaggle**

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
issues try to rename your file

**Comment by bidetaggle** [comment]
Hi @akshitagupta15june !

I noticed something:
- 26 days ago you assigned it to me: https://github.com/akshitagit/JavaScript/issues/45#issuecomment-699489711
- I made the PR 18 days ago
- You just accepted another PR submitted 2 days after mine: https://github.com/akshitagit/JavaScript/pull/92

And now you close mine because it has the same filename 😅

Anyway thank you for your time on this repo, I hope my comment can help :)

**Comment by akshitagupta15june** [comment]
i am very sorry @bidetaggle i am merging your pr too

**Comment by akshitagupta15june** [comment]
I have resolved the conflicts

**Comment by bidetaggle** [comment]
All good mate :)

**Pull request merged**
