### PR TITLE
hcf completed

### PR DESCRIPTION
**Pull request by grayTurtle01**
hcf completed :zany_face:

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Code is already there!

**Comment by akshitagupta15june** [comment]
Please work on different issue

**Comment by grayTurtle01** [comment]
Hey I did see it. :sob: 
But my code was make it in javaScript  and the code in the Folder Math is cpp
Can we push code in any language?

**Comment by akshitagupta15june** [comment]
i am sorry, i mistook.

**Comment by grayTurtle01** [comment]
Thank you. 
Im appreciate it
:smiley_cat:

**Pull request merged**
